config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'providers#index'

  resources :providers, except: [:destroy] do
    member do
      put 'status'
    end
  end

  resources :clients, except: [:destroy] do
    member do
      put 'status'
    end
  end

  resources :teams, except: [:show, :destroy] do
    member do
      put 'status'
    end
    resources :collaborators, shallow: true, except: [:destroy]
  end

  resources :collaborators, only: [] do
    put 'status', on: :member
  end

  resources :expenses, except: [:destroy] do
    collection do
      get 'provider_information'
      get 'collaborators_information'
    end
    member do
      get 'download'
    end
    resources :fees, shallow: true, except: [:destroy]
  end

  resources :incomes, except: [:destroy] do
    collection do
      get 'client_information'
    end
    member do
      get 'download'
      get 'generate_invoice'
    end
  end

  resources :parameters, except: [:new, :create, :destroy]

  resources :categories, except: [:destroy] do
    member do
      put 'status'
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord

  include SortableConcern

  belongs_to :country
  has_many :expenses
  has_many :incomes

  enum status: [:active, :desactive]

  validates :name, :address, :phone, presence: true
  validates :name, :corporate_name, :address, :contact, length: { maximum: 50 }
  validates :ruc, length: { maximum: 11 }
  validates :phone, length: { maximum: 10 }

  def self.filter_by_term(term)
    where("LOWER(clients.name) LIKE ?
      OR LOWER(clients.ruc) LIKE ?
      OR LOWER(clients.address) LIKE ?
      OR LOWER(clients.phone) LIKE ?",
      "%#{term.downcase}%", "%#{term.downcase}%", "%#{term.downcase}%",
      "%#{term.downcase}%")
    .group(:id)
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:show, :edit, :update, :status]

  helper_method :sort_column, :sort_direction

  def index
    @clients = Client.includes(:country).order(sort_column + ' ' + sort_direction)
    @clients = @clients.filter_by_term(params[:term]) if params[:term].present?
    @clients = @clients.paginate(per_page: 50, page: params[:page])

    respond_to do |f|
      f.html { render :index }
      f.js { render :index, layout: false }
    end
  end

  def show
  end

  def new
    @client = Client.new
    load_countries
  end

  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to clients_path, notice: "Successfully created"
    else
      render partial: 'errors/errors', locals: { resource: @client }
    end
  end

  def edit
    load_countries
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path, notice: "Successfully updated"
    else
      render partial: 'errors/errors', locals: { resource: @client }
    end
  end

  def status
    if @client.desactive?
      @client.active!
    else
      @client.desactive!
    end
    render :status, layout: false
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end


  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def sort_column
    Client.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def client_params
    params.require(:client).permit(:name, :ruc, :address, :phone, :contact, :country_id)
  end
end

app/views/clients/_client.haml
%tr{id: "#{dom_id client}", class: "#{color_tr(client)}"}
  %td= client.name
  %td= client.ruc.presence || '-'
  %td= client.address
  %td= client.phone
  %td= client.contact.presence || '-'
  %td= client.country.name
  %td
    = link_to client_path(client), class: 'black-text' do
      %i.material-icons visibility
    %span &nbsp;
    = link_to edit_client_path(client), class: 'black-text' do
      %i.material-icons edit
    %span &nbsp;
    = link_status(client)

app/views/clients/_form.haml
= form_for @client, remote: true do |f|
  .row
    .col.s12
      %span.bold (*) Required field

  #errors.red-text.center.bold.hidden An error occured

  .row.top-space
    .input-field.col.s12.m3
      = f.text_field :name, 'data-length': '50'
      = f.label :name, 'Name (*)'
      %small.red-text#name_error
    .input-field.col.s12.m3
      = f.text_field :corporate_name, 'data-length': '50'
      = f.label :corporate_name
      %small.red-text#corporate_name_error
    .input-field.col.s12.m3
      = f.text_field :ruc, 'data-length': '11'
      = f.label :ruc
      %small.red-text#ruc_error
    .input-field.col.s12.m3
      = f.select :country_id, options_from_collection_for_select(@countries,:id,:name,@client.country_id), prompt: 'Choose an option'
      = f.label :country_id, 'Country (*)'
      %small.red-text#country_id_error

  .row
    .input-field.col.s12.m3
      = f.text_field :address, 'data-length': '50'
      = f.label :address, 'Address (*)'
      %small.red-text#address_error
    .input-field.col.s12.m3
      = f.text_field :phone, 'data-length': '10'
      = f.label :phone, 'Phone (*)'
      %small.red-text#phone_error
    .input-field.col.s12.m3
      = f.text_field :contact, 'data-length': '50'
      = f.label :contact
      %small.red-text#contact_error

app/views/clients/_table_header.haml
%tr.pretty
  %th= sortable 'name', 'Name'
  %th= sortable 'ruc', 'RUC'
  %th= sortable 'address', 'Address'
  %th= sortable 'phone', 'Phone'
  %th= sortable 'contact', 'Contact'
  %th Country
  %th Actions

app/views/clients/edit.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Clients',clients_path, class: "breadcrumb blue-text"
            = link_to 'EDIT',edit_client_path(@client), class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: "edit_client_#{@client.id}"

    .row
      .col.s12
        = render 'form'

app/views/clients/index.haml
.fixed-action-btn.new-button
  = link_to new_client_path, class: "btn-floating waves-effect waves-light btn-large deep-purple accent-4 btn" do
    %i.material-icons add

.card.no-margin
  .card-content
    = form_tag clients_path, method: :get, remote: true do
      %p.bold.medium CLIENTS
      .row.no-margin
        .input-field.col.s12.no-padding.search-input
          %i.material-icons.prefix search
          = text_field_tag :term, params[:term]
          = label_tag :term, 'Search by name or ruc or address or phone'
      .row
        .col.s12.no-padding
          = button_tag :submit, "data-disable-with": "Searching ...", class: 'btn deep-purple accent-4 right' do
            Search

    = print_color_status

    .overflow-x
      %table.centered
        %thead#table_header
          = render 'table_header'
        %tbody#clients_index
          = render @clients

    .top-space.center.pagination-from-table
      = will_paginate @clients, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer

= render 'shareds/modal_confirmation'

app/views/clients/index.js.erb
$("#clients_index").html("<%= j render partial: 'client', collection: @clients, as: :client %>")
$('.pagination-from-table').html('<%= j will_paginate @clients, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer %>')
$("#table_header").html("<%= j render 'table_header' %>")

app/views/clients/new.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Clients',clients_path, class: "breadcrumb blue-text"
            = link_to 'ADD',new_client_path, class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: "new_client"
    .row
      .col.s12
        = render 'form'

app/views/clients/show.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12
            = link_to 'Clients',clients_path, class: "breadcrumb blue-text"
            = link_to @client.name,client_path(@client), class: "breadcrumb blue-text"
            = link_to 'VIEW','', class: "breadcrumb black-text"

    .row
      .col.s12.m4
        %span.bold Name
      .col.s12.m8
        %span= @client.name
    .row
      .col.s12.m4
        %span.bold Corporate name
      .col.s12.m8
        %span= @client.corporate_name.presence || '-'
    .row
      .col.s12.m4
        %span.bold RUC
      .col.s12.m8
        %span= @client.ruc.presence || '-'
    .row
      .col.s12.m4
        %span.bold Address
      .col.s12.m8
        %span= @client.address
    .row
      .col.s12.m4
        %span.bold Phone
      .col.s12.m8
        %span= @client.phone
    .row
      .col.s12.m4
        %span.bold Contact
      .col.s12.m8
        %span= @client.contact.presence || '-'
    .row
      .col.s12.m4
        %span.bold Country
      .col.s12.m8
        %span= @client.country.name

app/views/clients/status.js.erb
$("#<%= dom_id @client %>").replaceWith("<%= j render partial: 'client', locals: {client: @client} %>")
$("#modalConfirmation").modal('close')
Materialize.toast('Successfully <%= @client.status %>d', 4000)