config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'providers#index'

  resources :providers, except: [:destroy] do
    member do
      put 'status'
    end
  end

  resources :clients, except: [:destroy] do
    member do
      put 'status'
    end
  end

  resources :teams, except: [:show, :destroy] do
    member do
      put 'status'
    end
    resources :collaborators, shallow: true, except: [:destroy]
  end

  resources :collaborators, only: [] do
    put 'status', on: :member
  end

  resources :expenses, except: [:destroy] do
    collection do
      get 'provider_information'
      get 'collaborators_information'
    end
    member do
      get 'download'
    end
    resources :fees, shallow: true, except: [:destroy]
  end

  resources :incomes, except: [:destroy] do
    collection do
      get 'client_information'
    end
    member do
      get 'download'
      get 'generate_invoice'
    end
  end

  resources :parameters, except: [:new, :create, :destroy]

  resources :categories, except: [:destroy] do
    member do
      put 'status'
    end
  end
end

app/models/income.rb
# INCOMES AND EXPENSES COULD BE IN ONE MODEL (TRANSACTION), HOWEVER I THINK IN THE FUTURE INCOMES AND EXPENSES WILL HAVE DIFFERENT LOGIC OF DRASTIC WAY
# ALSO, THERE WILL BE TOO MANY RECORDS IN DATABASES
class Income < ApplicationRecord

  include ActionView::Helpers::NumberHelper

  belongs_to :client
  belongs_to :country
  belongs_to :currency
  belongs_to :team, optional: true
  belongs_to :collaborator, optional: true

  enum state: [:pending, :paid, :overdued]
  enum source: [:invoice, :other]

  validates :description, :amount, :billing_at, :registered_at, presence: true
  validates :amount, numericality: { greater_than: 0 }
  validates :invoice_copy, :invoice_number, :igv, presence: true, if: :invoice?
  validates :igv, numericality: { less_than_or_equal_to: 100, greater_than_or_equal_to: 0 }, if: :invoice?

  has_attached_file :invoice_copy, default_url: "/images/default.png"
  validates_attachment_content_type :invoice_copy, content_type: /\Aimage\/.*\z/

  has_attached_file :purchase_order, default_url: "/images/default.png"
  validates_attachment_content_type :purchase_order, content_type: /\Aimage\/.*\z/

  before_save :set_transaction_at
  after_initialize :set_defaults
  after_save :clear_tmp_images

  # improve invoice_copy_cache and purchase_order_cache
  # try to develop a concern
  attr_accessor :invoice_copy_cache, :purchase_order_cache

  def self.registered_from(from_date)
    if from_date.present?
      where("incomes.registered_at >= ?", from_date.to_datetime)
    else
      where("incomes.registered_at >= ?", Date.today.to_datetime.beginning_of_month)
    end
  end

  def self.registered_to(to_date)
    if to_date.present?
      where("incomes.registered_at <= ?", to_date.to_datetime.end_of_day)
    else
      where("incomes.registered_at <= ?", Date.today.end_of_day.to_datetime)
    end
  end

  def self.billing_from(from_date)
    where("incomes.billing_at >= ?", from_date.to_datetime)
  end

  def self.billing_to(from_date)
    where("incomes.billing_at <= ?", from_date.to_datetime.end_of_day)
  end

  def self.filter_by_state(state)
    send(state)
  end

  def self.filter_by_source(source)
    send(source)
  end

  def self.filter_by_country(country)
    joins(:country).where('LOWER(countries.name) = ?',country.try(:downcase) || 'Peru'.downcase).distinct
  end

  def self.filter_by_currency(currency)
    where('incomes.currency_id = ?',currency)
  end

  def self.calculate_total_soles
    where(currency_id: Currency.find_by_code('PEN')).sum("incomes.amount")
  end

  def self.calculate_total_dollar
    where(currency_id: Currency.find_by_code('USD')).sum("incomes.amount")
  end

  def self.calculate_total_dollar_in_soles
    calculate_total_dollar * Parameter.rate_of_change.last.value.to_f || 0
  end

  def self.calculate_total_in_soles
    calculate_total_soles + calculate_total_dollar_in_soles
  end

  def amount_decimal
    number_with_precision(amount, :precision => 2) || 0
  end

  def calculate_igv_amount
    ((self.amount || 0) * ((self.igv || 0) / 100)).round(2)
  end

  def calculate_total
    ((self.amount || 0) + calculate_igv_amount).round(2)
  end

  def cache_images_invoice_copy
    directory_name = 'public/system/incomes/invoice_copies/original'
    FileUtils.mkdir_p directory_name unless File.exists?(directory_name)
    if invoice_copy.staged?
      if invalid?
        FileUtils.cp(invoice_copy.queued_for_write[:original].path, invoice_copy.path(:original))
        @invoice_copy_cache = invoice_copy.path(:original)
      end
    else
      if @invoice_copy_cache.present?
        File.open(@invoice_copy_cache) {|f| assign_attributes(invoice_copy: f)}
      end
    end
  end

  def cache_images_purchase_order
    directory_name = 'public/system/incomes/purchase_orders/original'
    FileUtils.mkdir_p directory_name unless File.exists?(directory_name)
    if purchase_order.staged?
      if invalid?
        FileUtils.cp(purchase_order.queued_for_write[:original].path, purchase_order.path(:original))
        @purchase_order_cache = purchase_order.path(:original)
      end
    else
      if @purchase_order_cache.present?
        File.open(@purchase_order_cache) {|f| assign_attributes(purchase_order: f)}
      end
    end
  end

  private
  def set_transaction_at
    self.transaction_at = nil if self.overdued?
  end

  def set_defaults
    (self.igv ||=  Parameter.igv.last.value) if self.invoice?
    self.registered_at ||= Time.now
  end

  def clear_tmp_images
    directory_names = ['public/system/incomes/invoice_copies/original','public/system/incomes/purchase_orders/original']
    directory_names.each do |directory|
      Dir["#{directory}/*"].each{|file| FileUtils.rm file}
    end
  end

end

app/controllers/incomes_controller.rb
require "#{Rails.root}/app/views/pdfs/invoice_pdf.rb"

class IncomesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_income, only: [:show, :edit, :update, :download,:generate_invoice]

  helper_method :sort_column, :sort_direction

  def index
    if !request.xhr?
      load_countries_with_income
      load_currencies
    end

    @incomes = Income.includes(:client, :currency).order(sort_column + ' ' + sort_direction)
    @incomes = @incomes.registered_from(params[:registered_from]).registered_to(params[:registered_to]).filter_by_country(params[:country])
    @incomes = @incomes.billing_from(params[:billing_from]) unless params[:billing_from].blank?
    @incomes = @incomes.billing_to(params[:billing_to]) unless params[:billing_to].blank?
    @incomes = @incomes.filter_by_currency(params[:currency]) unless params[:currency].blank?
    @incomes = @incomes.filter_by_state(params[:state]) unless params[:state].blank?
    @incomes = @incomes.filter_by_source(params[:source]) unless params[:source].blank?
    @incomes = @incomes.paginate(per_page: 30, page: params[:page])

    respond_to do |f|
      f.html { render :index }
      f.js { render :index, layout: false }
    end

  end

  def new
    @income = Income.new
    load_countries
    load_clients
    load_currencies
  end

  def create
    @income = Income.new(income_params)
    @income.cache_images_invoice_copy
    @income.cache_images_purchase_order

    if @income.save
      redirect_to incomes_path, notice: 'Successfully created'
    else
      load_countries
      load_clients
      load_currencies
      render :new
    end
  end

  def edit
    load_countries
    load_clients
    load_currencies
  end

  def update
    @income.cache_images_invoice_copy
    @income.cache_images_purchase_order
    if @income.update(income_params)
      redirect_to incomes_path, notice: 'Successfully updated'
    else
      load_countries
      load_clients
      load_currencies
      render :edit
    end
  end

  def download
    begin
      if params[:document].present?
        send_file @income.send(params[:document]).path, filename: @income.send(params[:document]).original_filename
      else
        render nothing: true, status: 204, notice: "Nothing to download"
      end
    rescue StandardError => error
      render nothing: true, status: 204, notice: "Nothing to download"
    end
  end

  def generate_invoice
    respond_to do |format|
      format.pdf do
        pdf = InvoicePDF.new(@income)
        send_data pdf.render, filename: "INVOICE_#{@income.invoice_number}.pdf", type: 'application/pdf'
      end
    end
  end

  def client_information
    @client = Client.find_by_id(params[:client_id])
    render :client_information, layout: false
  end

  private
  def set_income
    @income = Income.find(params[:id])
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def sort_column
    Income.column_names.include?(params[:sort]) ? params[:sort] : "amount"
  end

  def income_params
    params.require(:income).permit(:income_id, :country_id, :invoice_number, :client_id,
                                    :source, :description, :currency_id, :amount, :igv,
                                    :billing_at, :registered_at, :purchase_order, :purchase_order_cache,
                                    :purchase_order_number,:invoice_copy, :invoice_copy_cache,
                                    :state,:note, :drawdown_seal)
  end
end

app/helpers/income_helper.rb
module IncomeHelper

  def color_state_of_income(income)
    return 'amber' if income.pending?
    return 'green' if income.paid?
    return 'red' if income.overdued?
  end

  def print_color_state_of_income
    content_tag(:div, class: 'top-space') do
      content_tag(:div,nil, class: 'color-state amber border-space')+
      content_tag(:span, 'Pending', class: 'little-left-space')+

      content_tag(:div,nil, class: 'color-state green little-left-space')+
      content_tag(:span, 'Paid', class: 'little-left-space') +

      content_tag(:div,nil, class: 'color-state red little-left-space')+
      content_tag(:span, 'Overdued', class: 'little-left-space')
    end
  end

  def label_amount(income)
    return 'Subtotal' if income.invoice?
    return 'Total'
  end

end

app/views/incomes/_filters.haml
= form_tag incomes_path, method: :get, remote: true, id: 'search_form' do
  .row
    .input-field.col.s12.m3
      = select_tag :country, options_from_collection_for_select(@countries,:name,:name, 'Peru'), class: 'send-filter'
      = label_tag :country, 'By country'
    .input-field.col.s12.m3
      = text_field_tag :registered_from, Date.today.to_date.beginning_of_month, class: 'datepicker send-filter'
      = label_tag :registered_from
    .input-field.col.s12.m3
      = text_field_tag :registered_to, Date.today.to_date, class: 'datepicker send-filter'
      = label_tag :registered_to
    .input-field.col.s12.m3
      = select_tag :currency, options_from_collection_for_select(@currencies,:id,:name, params[:currency]), prompt: 'Choose an option', class: 'send-filter'
      = label_tag :currency, 'By currency'
  .row
    .input-field.col.s12.m3
      = text_field_tag :billing_from, '', class: 'datepicker send-filter'
      = label_tag :billing_from
    .input-field.col.s12.m3
      = text_field_tag :billing_to, '', class: 'datepicker send-filter'
      = label_tag :billing_to
    .input-field.col.s12.m3
      = select_tag :state, options_for_select(class_enum_for_select("Income","state")), prompt: 'Select a state', class: 'send-filter'
      = label_tag :state, 'By state'
    .input-field.col.s12.m3
      = select_tag :source, options_for_select(class_enum_for_select('Income','source')), prompt: 'Choose an option', class: 'send-filter'
      = label_tag :source, 'By proof of payment'

  = hidden_field_tag :sort, params[:sort], id: 'sort_hidden'
  = hidden_field_tag :direction, params[:direction], id: 'direction_hidden'

app/views/incomes/_form.haml
= form_for @income, multipart: true do |f|
  .row
    .col.s12
      %span.bold (*) Required field

  - if @income.errors.any?
    #errors.red-text.center.bold An error occured

  .row.top-space
    .input-field.col.s12.m4
      = f.select :source, options_for_select(Income.sources.keys,@income.source),{}, class: 'source-select'
      = f.label :source, 'Proof of payment(*)'
      %small.red-text#source_error= @income.errors.full_messages_for(:source).to_sentence
    .input-field.col.s12.m4.fields-with-invoice{class: "#{'hidden' if @income.other? }"}
      = f.text_field :invoice_number, data: { length: '50' }
      = f.label :invoice_number, 'Invoice number (*)', class: 'active'
      %small.red-text#invoice_number_error= @income.errors.full_messages_for(:invoice_number).to_sentence
    .input-field.col.s12.m4
      = f.select :client_id, options_from_collection_for_select(@clients,:id,:name,@income.client_id), {prompt: 'Choose an option'}, class: 'client-select-income'
      = f.label :client_id, 'Client (*)'
      %small.red-text#client_error= @income.errors.full_messages_for(:client).to_sentence
      = link_to 'More', client_information_incomes_path, remote: true, class: 'hidden', id: 'client_information_link'

  .row
    .input-field.col.s12.m3
      = f.select :country_id, options_from_collection_for_select(@countries,:id,:name,@income.country_id),{ prompt: 'Choose an option' }, class: 'country-select'
      = f.label :country_id, 'Country (*)'
      %small.red-text#country_error= @income.errors.full_messages_for(:country).to_sentence
    #client_information{class: "#{'hidden' unless @income.client_id.present?}" }
      .input-field.col.s12.m3
        = text_field_tag :ruc, @income.client.try(:ruc), class: 'ruc-field', disabled: true
        = label_tag :ruc, 'RUC or DNI'
      .input-field.col.s12.m3
        = text_field_tag :address, @income.client.try(:address), class: 'address-field', disabled: true
        = label_tag :address, 'Client address'
      .input-field.col.s12.m3
        = text_field_tag :phone, @income.client.try(:phone), class: 'phone-field', disabled: true
        = label_tag :phone, 'Client phone'

  .row
    .input-field.col.s12.m4
      = f.text_field :description, data: { length: '200'}
      = f.label :description, 'Description (*)', class: 'active'
      %small.red-text#description_error= @income.errors.full_messages_for(:description).to_sentence
    .input-field.col.s12.m4
      = f.select :currency_id, options_from_collection_for_select(@currencies,:id,:name,@income.currency_id)
      = f.label :currency_id, 'Currency (*)'
      %small.red-text#currency_error= @income.errors.full_messages_for(:currency).to_sentence
  .row
    .input-field.col.s12.m4
      = f.number_field :amount, step: 'any', class: 'subtotal-field'
      = f.label :amount, label_amount(@income), class: 'active subtotal-label'
      %small.red-text#amount_error= @income.errors.full_messages_for(:amount).to_sentence
    .fields-with-invoice{class: "#{'hidden' if @income.other? }"}
      .input-field.col.s12.m1
        = f.number_field :igv, step: 'any', class: 'igv-field'
        = f.label :igv, 'I.G.V. (%)', class: 'active'
        %small.red-text#igv_error= @income.errors.full_messages_for(:igv).to_sentence
      .input-field.col.s12.m3
        = number_field_tag :igv_amount, @income.calculate_igv_amount, step: 'any', class: 'igv-amount-field', disabled: true
        = label_tag :igv_amount, 'IGV amount', class: 'active'
      .input-field.col.s12.m4
        = number_field_tag :total, @income.calculate_total, step: 'any', class: 'total-field', disabled: true
        = label_tag :total, 'Total', class: 'active'
  .row
    .col.s12.m6
      .file-field.input-field
        .btn.deep-purple.accent-4
          %span Invoice copy
          = f.file_field :invoice_copy
          = f.hidden_field :invoice_copy_cache
        .file-path-wrapper
          %input{type: 'text', class: 'file-path validate', value: @income.invoice_copy.original_filename}
      %small.red-text#invoice_copy_error= @income.errors.full_messages_for(:invoice_copy).to_sentence
    .col.s12.m6
      .file-field.input-field
        .btn.deep-purple.accent-4
          %span Purchase order
          = f.file_field :purchase_order
          = f.hidden_field :purchase_order_cache
        .file-path-wrapper
          %input{type: 'text', class: 'file-path validate', value: @income.purchase_order.original_filename}
      %small.red-text#purchase_order_error= @income.errors.full_messages_for(:purchase_order).to_sentence

  .row
    .input-field.col.s12.m4
      = f.text_field :purchase_order_number
      = f.label :purchase_order_number, class: 'active'
      %small.red-text#purchase_order_number_error= @income.errors.full_messages_for(:purchase_order_number).to_sentence
    .input-field.col.s12.m4
      = f.text_field :billing_at, class: 'datepicker', value: @income.billing_at.try(:strftime,"%Y-%m-%d")
      = f.label :billing_at, 'Billing at (*)', class: 'active'
      %small.red-text#billing_at_error= @income.errors.full_messages_for(:billing_at).to_sentence
    .input-field.col.s12.m4
      = f.text_field :registered_at, class: 'datepicker', value: @income.registered_at.try(:strftime,"%Y-%m-%d")
      = f.label :registered_at, 'Registered at (*)', class: 'active'
      %small.red-text#registered_at_error= @income.errors.full_messages_for(:registered_at).to_sentence

  .row
    .col.s12.m4
      = f.check_box :drawdown_seal
      = f.label :drawdown_seal
  .row
    .input-field.col.s12.m4
      = f.select :state, class_enum_for_select("Income","state"), {}, class: 'send-filter'
      = label_tag :state, 'State(*)'
      %small.red-text#state_error= @income.errors.full_messages_for(:state).to_sentence
    .input-field.col.s12.m4
      = f.text_area :note, class: 'materialize-textarea'
      = f.label :note

app/views/incomes/_income.haml
%tr{id: "#{dom_id income}", class: "#{color_state_of_income(income)} %>"}
  %td= income.source.humanize
  %td= income.client.name
  %td= income.description
  %td= "#{income.currency.code} #{income.amount}"
  %td= income.created_at.strftime("%Y/%m/%d")
  %td= income.billing_at.strftime("%Y/%m/%d")
  %td= income.state
  %td
    = link_to "<i class='material-icons'>visibility</i>".html_safe, income_path(income), class: 'black-text'
    = link_to "<i class='material-icons'>picture_as_pdf</i>".html_safe, generate_invoice_income_path(income,format: :pdf), class: 'black-text'
    = link_to "<i class='material-icons'>edit</i>".html_safe, edit_income_path(income), class: 'black-text'

app/views/incomes/_table_header.haml
%tr.pretty
  %th= sortable_with_multiple_filter 'source', 'Source'
  %th Client
  %th Description
  %th= sortable_with_multiple_filter 'amount', 'Amount'
  %th= sortable_with_multiple_filter 'created_at', 'Creation Date'
  %th= sortable_with_multiple_filter 'billing_at', 'Billing date'
  %th State
  %th Actions

app/views/incomes/_total.haml
.row
  .col.s12
    %span.bold.border-collection TOTAL OF ALL INCOMES
.row
  .col.s12.m2
    %span.bold TOTAL (PEN):
  .col.s12.m2.right-text
    %span= number_with_precision(Income.calculate_total_soles, precision: 2)
.row
  .col.s12.m2
    %span.bold TOTAL (USD) IN PEN:
    = text_rate_of_change
  .col.s12.m2.right-text
    %span= number_with_precision(Income.calculate_total_dollar_in_soles, precision: 2)
.row
  .col.s12.m2
    %span.bold TOTAL IN PEN
    = text_rate_of_change
  .col.s12.m2.right-text
    %span= number_with_precision(Income.calculate_total_in_soles, precision: 2)

app/views/incomes/client_information.js.erb
<% if @client.present? %>
  $('.country-select').val("<%= @client.country_id %>").change()
  $('.ruc-field').val("<%= @client.ruc %>")
  $('.address-field').val("<%= @client.address %>")
  $('.phone-field').val("<%= @client.phone %>")
  $('#client_information').fadeIn()
  $('select').material_select()
  Materialize.updateTextFields()
<% end %>

app/views/incomes/edit.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Incomes', incomes_path, class: "breadcrumb blue-text"
            = link_to 'EDIT',edit_income_path(@income), class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: "edit_income_#{@income.id}"

    .row
      .col.s12.form-wrapper
        = render 'form'

app/views/incomes/index.haml
.fixed-action-btn.new-button
  = link_to new_income_path, class: "btn-floating waves-effect waves-light btn-large deep-purple accent-4 btn" do
    %i.material-icons add

.card.no-margin
  .card-content
    %p.bold.medium INCOMES
    = render 'filters'

    = print_color_state_of_income

    .overflow-x
      %table.centered
        %thead#table_header
          = render 'table_header'
        %tbody#incomes_index
          = render @incomes

    .top-space.center.pagination-from-table
      = will_paginate @incomes, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer

    #total
      = render 'total'

app/views/incomes/index.js.erb
$("#incomes_index").html("<%= j render partial: 'income', collection: @incomes, as: :income %>")
$('.pagination-from-table').html('<%= j will_paginate @incomes, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer %>')
$("#table_header").html("<%= j render 'table_header' %>")

app/views/incomes/new.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Incomes', incomes_path, class: "breadcrumb blue-text"
            = link_to 'ADD', new_income_path, class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: "new_income"
    .row
      .col.s12.form-wrapper
        = render 'form'

app/views/incomes/show.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12
            = link_to 'Incomes',incomes_path, class: "breadcrumb blue-text"
            = link_to @income.description.truncate(25),income_path(@income), class: "breadcrumb blue-text"
            = link_to 'VIEW','', class: "breadcrumb black-text"

    .row
      .col.s12.m4
        %span.bold Source:
      .col.s12.m8
        %span= @income.source.humanize
    .row
      .col.s12.m4
        %span.bold State
      .col.s12.m8
        %span= @income.state.humanize

    .row
      .col.s12.m4
        %span.bold Invoice number:
      .col.s12.m8
        %span= @income.invoice_number

    .row
      .col.s12.m4
        %span.bold Client name:
      .col.s12.m8
        %span= @income.client.name

    .row
      .col.s12.m4
        %span.bold Country:
      .col.s12.m8
        %span= @income.country.name

    .row
      .col.s12.m4
        %span.bold Description:
      .col.s12.m8
        %span= @income.description

    .row
      .col.s12.m4
        %span.bold Amount:
      .col.s12.m8
        %span= "#{@income.currency.code} #{@income.amount}"

    .row
      .col.s12.m4
        %span.bold Purchase order number:
      .col.s12.m8
        %span= @income.purchase_order_number

    .row
      .col.s12.m4
        %span.bold Billing date (yyyy-mm-dd):
      .col.s12.m8
        %span= @income.billing_at.strftime("%Y-%m-%d")

    .row
      .col.s12.m4
        %span.bold Invoice copy:
      .col.s12.m8
        %span
          - if @income.invoice_copy.present?
            = link_to @income.invoice_copy.original_filename, download_income_path(@income,document: 'invoice_copy'), target: '_blank'
          - else
            -

    .row
      .col.s12.m4
        %span.bold Purchase order:
      .col.s12.m8
        %span
        - if @income.purchase_order.present?
          = link_to @income.purchase_order.original_filename, download_income_path(@income,document: 'purchase_order'), target: '_blank'
        -else
          -

    .row
      .col.s12.m4
        %span.bold Drawdown seal:
      .col.s12.m8
        %span= @income.drawdown_seal.humanize

    .row
      .col.s12.m4
        %span.bold Note:
      .col.s12.m8
        %span.multiple-line= @income.note