config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'providers#index'

  resources :providers, except: [:destroy] do
    member do
      put 'status'
    end
  end

  resources :clients, except: [:destroy] do
    member do
      put 'status'
    end
  end

  resources :teams, except: [:show, :destroy] do
    member do
      put 'status'
    end
    resources :collaborators, shallow: true, except: [:destroy]
  end

  resources :collaborators, only: [] do
    put 'status', on: :member
  end

  resources :expenses, except: [:destroy] do
    collection do
      get 'provider_information'
      get 'collaborators_information'
    end
    member do
      get 'download'
    end
    resources :fees, shallow: true, except: [:destroy]
  end

  resources :incomes, except: [:destroy] do
    collection do
      get 'client_information'
    end
    member do
      get 'download'
      get 'generate_invoice'
    end
  end

  resources :parameters, except: [:new, :create, :destroy]

  resources :categories, except: [:destroy] do
    member do
      put 'status'
    end
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title Finance
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    #notice{style: 'display: none'}= flash[:notice]

    - if user_signed_in?
      .navbar-fixed
        %nav.white
          .nav-wrapper
            = link_to 'Finance', root_path, class: 'black-text text-logo'
            %ul.right.hide-on-med-and-down
              %li
                = link_to destroy_user_session_path, method: :delete, class: 'black-text' do
                  Logout
                  %i.material-icons.right input

      .row.no-margin.full-height
        .col.s3.m2.no-padding.full-height.custom-color
          .collection.no-margin.custom-color#options

            = li_paint_slider 'TEAMS', teams_path, 'teams'
            = li_paint_slider 'CATEGORIES', categories_path, 'categories'
            = li_paint_slider 'CLIENTS', clients_path, 'clients'
            = li_paint_slider 'PROVIDERS', providers_path, 'providers'
            = li_paint_slider 'INCOMES', incomes_path, 'incomes'
            = li_paint_slider 'EXPENSES', expenses_path, 'expenses'
            = li_paint_slider 'PARAMETERS', parameters_path, 'parameters'

        .col.s9.m10.no-padding.full-height#main
          = yield
          %div{style: "height: 4.5em"}
    - else
      = yield